---
title: "autorecipes"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{autorecipes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(autorecipes)
library(magrittr)
```

# Usage

## Set of example recipes

```{r recipebook-example}

recipebook <- recipebook_example

recipes(recipebook) %>% head()
```

## Set your favourite recipes

```{r set-favourite}

favourites(recipebook) <- 1:3

recipes(recipebook) %>% head()
```

## Create a meal plan

```{r create-meal-plan}

recipebook <- create_meal_plan(
  recipebook,
  days = c("Wed", "Thurs", "Fri", "Sat", "Sun"), meals = "Dinner",
  fav_only = TRUE
)

meal_plan(recipebook)
```

## Create shopping list

```{r create-shopping-list}

# x <- create_shopping_list(recipebook, method = "manual")
# x %>% readr::write_delim("/Users/david_zhang/Downloads/shopping_list_dz_cjkg.txt", delim = "\t")
```
